spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://数据库服务器地址:3306/qukuailian?useUnicode=true&useSSL=false&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: 用户名
    password: 密码
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 10000
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level%logger{36}%n\t%msg%n"
  level:
    top:
      blockchain: INFO
  file: logs/qukuailian.log
mybatis:
  config-location: classpath:mybatis-config.xml